feat(auth): Invite and register process
antify/antify pull request #35
Opened 2022-07-28 08:07 UTC by ThomasKro

- implemented user invite process
- implemented send mail to invited user
- implemented register for new user (currenlty needs token)
- fixed tenant issues

2022-07-29 06:56 UTC, ThomasKro commented
@beyer-johannes updated the invite process, now you can review

2022-07-29 08:22 UTC, beyer-johannes requested changes

2022-07-29 08:22 UTC, beyer-johannes commented on packages/antify-admin/src/server/api/global/tenants.get.ts
> +  // TODO:: User should always have read access to tenants he is assigned to.
gruad.hasPermissionTo check this already

2022-07-29 08:22 UTC, beyer-johannes commented on packages/antify-admin/src/server/datasources/auth/migrations/20220729052805_init/migration.sql
> +    `password` VARCHAR(191) NULL DEFAULT '',
Why?

2022-08-01 08:30 UTC, ThomasKro commented on packages/antify-admin/src/server/datasources/auth/migrations/20220729052805_init/migration.sql
> +    `password` VARCHAR(191) NULL DEFAULT '',
Because

2022-08-01 09:06 UTC, beyer-johannes approved these changes

2022-08-01 09:06 UTC, merged